/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kc_storage_TYPES_H
#define kc_storage_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace KC_Storage {

struct putOption {
  enum type {
    add = 0,
    update = 1,
    remove = 2
  };
};

extern const std::map<int, const char*> _putOption_VALUES_TO_NAMES;
} // namespace

#endif
