/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kc_storage_types.h"

#include <algorithm>

namespace KC_Storage {

int _kputOptionValues[] = {
  putOption::add,
  putOption::update,
  putOption::overide
};
const char* _kputOptionNames[] = {
  "add",
  "update",
  "overide"
};
const std::map<int, const char*> _putOption_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kputOptionValues, _kputOptionNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

} // namespace
