/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef KC_Storage_H
#define KC_Storage_H

#include <thrift/TDispatchProcessor.h>
#include "kc_storage_types.h"

namespace KC_Storage {

class KC_StorageIf {
 public:
  virtual ~KC_StorageIf() {}
  virtual void get(std::string& _return, const std::string& key) = 0;
  virtual bool put(const std::string& key, const std::string& value, const putOption::type opt) = 0;
  virtual bool remove(const std::string& key) = 0;
};

class KC_StorageIfFactory {
 public:
  typedef KC_StorageIf Handler;

  virtual ~KC_StorageIfFactory() {}

  virtual KC_StorageIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(KC_StorageIf* /* handler */) = 0;
};

class KC_StorageIfSingletonFactory : virtual public KC_StorageIfFactory {
 public:
  KC_StorageIfSingletonFactory(const boost::shared_ptr<KC_StorageIf>& iface) : iface_(iface) {}
  virtual ~KC_StorageIfSingletonFactory() {}

  virtual KC_StorageIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(KC_StorageIf* /* handler */) {}

 protected:
  boost::shared_ptr<KC_StorageIf> iface_;
};

class KC_StorageNull : virtual public KC_StorageIf {
 public:
  virtual ~KC_StorageNull() {}
  void get(std::string& /* _return */, const std::string& /* key */) {
    return;
  }
  bool put(const std::string& /* key */, const std::string& /* value */, const putOption::type /* opt */) {
    bool _return = false;
    return _return;
  }
  bool remove(const std::string& /* key */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _KC_Storage_get_args__isset {
  _KC_Storage_get_args__isset() : key(false) {}
  bool key;
} _KC_Storage_get_args__isset;

class KC_Storage_get_args {
 public:

  KC_Storage_get_args() : key() {
  }

  virtual ~KC_Storage_get_args() throw() {}

  std::string key;

  _KC_Storage_get_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  bool operator == (const KC_Storage_get_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const KC_Storage_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KC_Storage_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KC_Storage_get_pargs {
 public:


  virtual ~KC_Storage_get_pargs() throw() {}

  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KC_Storage_get_result__isset {
  _KC_Storage_get_result__isset() : success(false) {}
  bool success;
} _KC_Storage_get_result__isset;

class KC_Storage_get_result {
 public:

  KC_Storage_get_result() : success() {
  }

  virtual ~KC_Storage_get_result() throw() {}

  std::string success;

  _KC_Storage_get_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const KC_Storage_get_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const KC_Storage_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KC_Storage_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KC_Storage_get_presult__isset {
  _KC_Storage_get_presult__isset() : success(false) {}
  bool success;
} _KC_Storage_get_presult__isset;

class KC_Storage_get_presult {
 public:


  virtual ~KC_Storage_get_presult() throw() {}

  std::string* success;

  _KC_Storage_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _KC_Storage_put_args__isset {
  _KC_Storage_put_args__isset() : key(false), value(false), opt(false) {}
  bool key;
  bool value;
  bool opt;
} _KC_Storage_put_args__isset;

class KC_Storage_put_args {
 public:

  KC_Storage_put_args() : key(), value(), opt((putOption::type)0) {
  }

  virtual ~KC_Storage_put_args() throw() {}

  std::string key;
  std::string value;
  putOption::type opt;

  _KC_Storage_put_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  void __set_value(const std::string& val) {
    value = val;
  }

  void __set_opt(const putOption::type val) {
    opt = val;
  }

  bool operator == (const KC_Storage_put_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(opt == rhs.opt))
      return false;
    return true;
  }
  bool operator != (const KC_Storage_put_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KC_Storage_put_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KC_Storage_put_pargs {
 public:


  virtual ~KC_Storage_put_pargs() throw() {}

  const std::string* key;
  const std::string* value;
  const putOption::type* opt;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KC_Storage_put_result__isset {
  _KC_Storage_put_result__isset() : success(false) {}
  bool success;
} _KC_Storage_put_result__isset;

class KC_Storage_put_result {
 public:

  KC_Storage_put_result() : success(0) {
  }

  virtual ~KC_Storage_put_result() throw() {}

  bool success;

  _KC_Storage_put_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const KC_Storage_put_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const KC_Storage_put_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KC_Storage_put_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KC_Storage_put_presult__isset {
  _KC_Storage_put_presult__isset() : success(false) {}
  bool success;
} _KC_Storage_put_presult__isset;

class KC_Storage_put_presult {
 public:


  virtual ~KC_Storage_put_presult() throw() {}

  bool* success;

  _KC_Storage_put_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _KC_Storage_remove_args__isset {
  _KC_Storage_remove_args__isset() : key(false) {}
  bool key;
} _KC_Storage_remove_args__isset;

class KC_Storage_remove_args {
 public:

  KC_Storage_remove_args() : key() {
  }

  virtual ~KC_Storage_remove_args() throw() {}

  std::string key;

  _KC_Storage_remove_args__isset __isset;

  void __set_key(const std::string& val) {
    key = val;
  }

  bool operator == (const KC_Storage_remove_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const KC_Storage_remove_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KC_Storage_remove_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KC_Storage_remove_pargs {
 public:


  virtual ~KC_Storage_remove_pargs() throw() {}

  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KC_Storage_remove_result__isset {
  _KC_Storage_remove_result__isset() : success(false) {}
  bool success;
} _KC_Storage_remove_result__isset;

class KC_Storage_remove_result {
 public:

  KC_Storage_remove_result() : success(0) {
  }

  virtual ~KC_Storage_remove_result() throw() {}

  bool success;

  _KC_Storage_remove_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const KC_Storage_remove_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const KC_Storage_remove_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KC_Storage_remove_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KC_Storage_remove_presult__isset {
  _KC_Storage_remove_presult__isset() : success(false) {}
  bool success;
} _KC_Storage_remove_presult__isset;

class KC_Storage_remove_presult {
 public:


  virtual ~KC_Storage_remove_presult() throw() {}

  bool* success;

  _KC_Storage_remove_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class KC_StorageClient : virtual public KC_StorageIf {
 public:
  KC_StorageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  KC_StorageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get(std::string& _return, const std::string& key);
  void send_get(const std::string& key);
  void recv_get(std::string& _return);
  bool put(const std::string& key, const std::string& value, const putOption::type opt);
  void send_put(const std::string& key, const std::string& value, const putOption::type opt);
  bool recv_put();
  bool remove(const std::string& key);
  void send_remove(const std::string& key);
  bool recv_remove();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class KC_StorageProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<KC_StorageIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (KC_StorageProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_put(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_remove(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  KC_StorageProcessor(boost::shared_ptr<KC_StorageIf> iface) :
    iface_(iface) {
    processMap_["get"] = &KC_StorageProcessor::process_get;
    processMap_["put"] = &KC_StorageProcessor::process_put;
    processMap_["remove"] = &KC_StorageProcessor::process_remove;
  }

  virtual ~KC_StorageProcessor() {}
};

class KC_StorageProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  KC_StorageProcessorFactory(const ::boost::shared_ptr< KC_StorageIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< KC_StorageIfFactory > handlerFactory_;
};

class KC_StorageMultiface : virtual public KC_StorageIf {
 public:
  KC_StorageMultiface(std::vector<boost::shared_ptr<KC_StorageIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~KC_StorageMultiface() {}
 protected:
  std::vector<boost::shared_ptr<KC_StorageIf> > ifaces_;
  KC_StorageMultiface() {}
  void add(boost::shared_ptr<KC_StorageIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void get(std::string& _return, const std::string& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, key);
    }
    ifaces_[i]->get(_return, key);
    return;
  }

  bool put(const std::string& key, const std::string& value, const putOption::type opt) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->put(key, value, opt);
    }
    return ifaces_[i]->put(key, value, opt);
  }

  bool remove(const std::string& key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->remove(key);
    }
    return ifaces_[i]->remove(key);
  }

};

} // namespace

#endif
