/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kc_storage_CONSTANTS_H
#define kc_storage_CONSTANTS_H

#include "kc_storage_types.h"

namespace KC_Storage {

class kc_storageConstants {
 public:
  kc_storageConstants();

};

extern const kc_storageConstants g_kc_storage_constants;

} // namespace

#endif
