/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kc_storage_constants.h"

namespace KC_Storage {

const kc_storageConstants g_kc_storage_constants;

kc_storageConstants::kc_storageConstants() {
}

} // namespace

